---
- name: Installing and Launch Filebeat
  hosts: webservers
  become: yes
  tasks:
    # Use command module
  - name: Download filebeat .rpm file
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-oss-7.8.1-x86_64.rpm

    # Use command module
  - name: Install filebeat .rpm
    command: sudo rpm -vi metricbeat-oss-7.8.1-x86_64.rpm

    # Use copy module
  - name: Drop in metricbeat.yml
    copy:
      src: /etc/ansible/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml

    # Use command module
  - name: Enable and Configure System Module
    command: metricbeat modules enable docker

    # Use command module
  - name: Setup filebeat
    command: metricbeat setup

    # Use command module
  - name: Start metricbeat service
    command: service metricbeat start

    # Use systemd module
  - name: Enable service metricbeat on boot
    systemd:
      name: metricbeat
      enabled: yes